- admin/diderot_admin
- api_calls.py
This PR adds a list_chapters command to make it easier to
select chapter numbers when uploading.
Additionally this PR updates the update_book command by requiring that
the user input the course, as well as asking the user for confirmation
before performing the upload.
> Admin: update QOL for update_book and add a list_chapters command

- admin/diderot_admin
- api_calls.py
In the process of doing this, a list_parts command has been added to the CLI as well.
> Adding a create_chapter CLI command.

- admin/diderot_admin
- diderot
- diderot_core.py
> Allowing for a simple credentials file

- admin/diderot_admin
- api_calls.py
Fixes #21.
This can only be landed once https://github.com/umutacar/lambdabricks/pull/1513 has been merged and deployed to production!
> admin: Remove part restriction on create chapter.

- admin/diderot_admin
- api_calls.py
Fixes #20.
This will only fully work once the filter PR on lambdabricks
lands into production.
> List books now uses similar syntax as the other commands.

- api_calls.py
> Removing littering logged in / logged out checks.

- admin/diderot_admin
- api_calls.py
> Adding a create_part command.

- diderot_core.py
Fixes #37.
By default, the CLI will look at ~/.diderot/credentials for login credentials. This can be overridden by passing in a username or password
> By default, the CLI will look at ~/.diderot/credentials.

- admin/diderot_admin
- diderot_core.py
> Progress towards nicer printing

- diderot_core.py
> Added clean tabular output for commands that display lists.

- api_calls.py
- diderot_admin
- diderot_student
- standalone.py
- test.py
- test_server.py
- testdata/autograde-Makefile
- testdata/autograde.tar
- testdata/book.mlx
- testdata/book.pdf
- testdata/book.xml
- testdata/chapter.pdf
- testdata/handout.tar
- testdata/images/test1.png
- testdata/images/test2.png
- testdata/slides.pdf
- testdata/test_handin.tar
- testdata/writeup.pdf
* Added parsing and structure for the standalone version of the CLI.
* Implemented the user version of the CLI.
* Implemented admin version of the CLI.
* Completed test suite for user version of the CLI.
* Completed test suite for the admin version of the CLI.
This PR adds the standalone versions of the CLI's, and fixes alot of bugs that the test suite found.
Work for #32 and #44.
> Making a standalone (not embedded) version of the CLI along with tests

- api_calls.py
- test.py
> Disallow part creation on booklets

- README.md
- standalone.py
> credentials: Require credentials file has restricted permissions.

- api_calls.py
- test.py
- test_server.py
> Add support for tar or fileupload handins.

- api_calls.py
- standalone.py
- test.py
> Return non-zero status code on failure

- api_calls.py
- standalone.py
- test.py
- test_server.py
Fixes https://github.com/diderot-edu/diderot-feedback/issues/6.
> Add support for releasing and unreleasing a chapter

- api_calls.py
- test.py
> api: update error message when course is not found

- api_calls.py
- standalone.py
- testdata/book-with-parts.json
This PR implements support book uploads with parts.  See  as example
```
testdata/book-with-parts.json
```
> Bulk book uploads

- constants.py
- test_server.py
Renamed API route from frontend-api to api.
Should be merged after https://github.com/umutacar/lambdabricks/pull/6552
> Changed API route (frontend-api -> api)

- api_calls.py
- models.py
- standalone.py
- test.py
requests remove booklets support and checks
> remove booklets

- diderot_cli/commands/diderot_admin.py
- diderot_cli/commands/diderot_user.py
- diderot_cli/utils.py
- requirements.txt
- test.py
> create command aliases for backward compatibility

- diderot_cli/commands/diderot_admin.py
- diderot_cli/models.py
- resources/makefile-upload-to-diderot
* update book JSON to use dashes instead of underscores for consistency with CLI commands
* catch connection exceptions
* misc fixes
> catch exceptions due to connection issues
